### PR TITLE
FAKE: test rubocop in jenkins

### PR DESCRIPTION
**Pull request by am-gd-cz**
beee

### CODE REVIEW

**Comment by rchrom** [comment]
ok to test

**Comment by rchrom** [comment]
ok to test

**Comment by rchrom** [comment]
ok to test

**Comment by am-gd-cz** [comment]
ok to test

**Comment by am-gd-cz** [comment]
ok to test

**Comment by am-gd-cz** [comment]
ok to test

**Comment by am-gd-cz** [comment]
ok to test

**Pull request closed without merging**
