### PR TITLE
FEATURE: QA-5572 - add rake tasks

### PR DESCRIPTION
**Pull request by am-gd-cz**

### CODE REVIEW

**Comment by yenkins-admin** [comment]
Test PASSed.
Refer to this link for build results: https://ci.intgdc.com/job/cmdline-tool-tests-pull-request-builder/2/

**Comment by ytsarev** [comment]
LGTM

**Comment by michalvanco** [comment]
Are you going to update documentation?

**Comment by yenkins-admin** [comment]
Merged build triggered.

**Comment by yenkins-admin** [comment]
Merged build started.

**Comment by yenkins-admin** [comment]
Merged build finished.

**Comment by yenkins-admin** [comment]
Test PASSed.
Refer to this link for build results: https://ci.intgdc.com/job/cmdline-tool-tests-pull-request-builder/3/

**Comment by am-gd-cz** [comment]
@michalvanco oh, now that you mention it. I'll do

**Comment by yenkins-admin** [comment]
Test PASSed.
Refer to this link for build results: https://ci.intgdc.com/job/cmdline-tool-tests-pull-request-builder/4/

**Comment by yenkins-admin** [comment]
Test PASSed.
Refer to this link for build results: https://ci.intgdc.com/job/cmdline-tool-tests-pull-request-builder/5/

**Comment by yenkins-admin** [comment]
Test PASSed.
Refer to this link for build results: https://ci.intgdc.com/job/cmdline-tool-tests-pull-request-builder/6/

**Pull request merged**
